[package]
name = "rust_regex"
version = "0.1.0"
authors = ["George Stacey <gs919@ic.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
